-- TEMPLATE ONLY: replace pending_star_v2 via prepare_star_binding.py after a verified v2 E2E run.
-- Run on LH_EV_Gold SQL analytics endpoint after SQL metadata synchronization.
-- These statements are read-only; all orphan/duplicate result counts must be zero.
SELECT COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f;

SELECT 'age_band' AS segment_dimension, d.age_band AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_demographics_pending_star_v2 d ON f.demographics_key = d.demographics_key GROUP BY d.age_band
UNION ALL
SELECT 'income_band' AS segment_dimension, d.income_band AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_income_pending_star_v2 d ON f.income_key = d.income_key GROUP BY d.income_band
UNION ALL
SELECT 'commute_band' AS segment_dimension, d.commute_band AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_mobility_pending_star_v2 d ON f.mobility_key = d.mobility_key GROUP BY d.commute_band
UNION ALL
SELECT 'Gender' AS segment_dimension, d.Gender AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_demographics_pending_star_v2 d ON f.demographics_key = d.demographics_key GROUP BY d.Gender
UNION ALL
SELECT 'City_Type' AS segment_dimension, d.City_Type AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_demographics_pending_star_v2 d ON f.demographics_key = d.demographics_key GROUP BY d.City_Type
UNION ALL
SELECT 'Current_Car_Type' AS segment_dimension, d.Current_Car_Type AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_mobility_pending_star_v2 d ON f.mobility_key = d.mobility_key GROUP BY d.Current_Car_Type
UNION ALL
SELECT 'Home_Charging_Possible' AS segment_dimension, d.Home_Charging_Possible AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_charging_pending_star_v2 d ON f.charging_key = d.charging_key GROUP BY d.Home_Charging_Possible
UNION ALL
SELECT 'Subsidy_Available' AS segment_dimension, d.Subsidy_Available AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_attitude_incentive_pending_star_v2 d ON f.attitude_incentive_key = d.attitude_incentive_key GROUP BY d.Subsidy_Available
UNION ALL
SELECT 'Range_Anxiety_Level' AS segment_dimension, d.Range_Anxiety_Level AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_attitude_incentive_pending_star_v2 d ON f.attitude_incentive_key = d.attitude_incentive_key GROUP BY d.Range_Anxiety_Level
UNION ALL
SELECT 'Environmental_Concern_Level' AS segment_dimension, d.Environmental_Concern_Level AS segment_value, COUNT(*) AS respondent_count, SUM(f.will_buy_ev_flag) AS yes_count, COUNT(*) - SUM(f.will_buy_ev_flag) AS no_count, 1.0 * SUM(f.will_buy_ev_flag) / NULLIF(COUNT(*), 0) AS purchase_intent_rate FROM dbo.fact_ev_purchase_intent_pending_star_v2 f JOIN dbo.dim_attitude_incentive_pending_star_v2 d ON f.attitude_incentive_key = d.attitude_incentive_key GROUP BY d.Environmental_Concern_Level;

SELECT 'dim_demographics' AS dimension_name, COUNT(*) AS orphan_count FROM dbo.fact_ev_purchase_intent_pending_star_v2 f LEFT JOIN dbo.dim_demographics_pending_star_v2 d ON f.demographics_key=d.demographics_key WHERE d.demographics_key IS NULL;
SELECT demographics_key, COUNT(*) AS duplicate_count FROM dbo.dim_demographics_pending_star_v2 GROUP BY demographics_key HAVING COUNT(*) > 1 OR demographics_key IS NULL;
SELECT 'dim_income' AS dimension_name, COUNT(*) AS orphan_count FROM dbo.fact_ev_purchase_intent_pending_star_v2 f LEFT JOIN dbo.dim_income_pending_star_v2 d ON f.income_key=d.income_key WHERE d.income_key IS NULL;
SELECT income_key, COUNT(*) AS duplicate_count FROM dbo.dim_income_pending_star_v2 GROUP BY income_key HAVING COUNT(*) > 1 OR income_key IS NULL;
SELECT 'dim_mobility' AS dimension_name, COUNT(*) AS orphan_count FROM dbo.fact_ev_purchase_intent_pending_star_v2 f LEFT JOIN dbo.dim_mobility_pending_star_v2 d ON f.mobility_key=d.mobility_key WHERE d.mobility_key IS NULL;
SELECT mobility_key, COUNT(*) AS duplicate_count FROM dbo.dim_mobility_pending_star_v2 GROUP BY mobility_key HAVING COUNT(*) > 1 OR mobility_key IS NULL;
SELECT 'dim_charging' AS dimension_name, COUNT(*) AS orphan_count FROM dbo.fact_ev_purchase_intent_pending_star_v2 f LEFT JOIN dbo.dim_charging_pending_star_v2 d ON f.charging_key=d.charging_key WHERE d.charging_key IS NULL;
SELECT charging_key, COUNT(*) AS duplicate_count FROM dbo.dim_charging_pending_star_v2 GROUP BY charging_key HAVING COUNT(*) > 1 OR charging_key IS NULL;
SELECT 'dim_attitude_incentive' AS dimension_name, COUNT(*) AS orphan_count FROM dbo.fact_ev_purchase_intent_pending_star_v2 f LEFT JOIN dbo.dim_attitude_incentive_pending_star_v2 d ON f.attitude_incentive_key=d.attitude_incentive_key WHERE d.attitude_incentive_key IS NULL;
SELECT attitude_incentive_key, COUNT(*) AS duplicate_count FROM dbo.dim_attitude_incentive_pending_star_v2 GROUP BY attitude_incentive_key HAVING COUNT(*) > 1 OR attitude_incentive_key IS NULL;

-- Expected 0 rows: compare every original business field with Silver.
SELECT COALESCE(f.id,s.id) AS mismatched_id FROM dbo.fact_ev_purchase_intent_pending_star_v2 f LEFT JOIN dbo.dim_demographics_pending_star_v2 d0 ON f.demographics_key=d0.demographics_key LEFT JOIN dbo.dim_income_pending_star_v2 d1 ON f.income_key=d1.income_key LEFT JOIN dbo.dim_mobility_pending_star_v2 d2 ON f.mobility_key=d2.mobility_key LEFT JOIN dbo.dim_charging_pending_star_v2 d3 ON f.charging_key=d3.charging_key LEFT JOIN dbo.dim_attitude_incentive_pending_star_v2 d4 ON f.attitude_incentive_key=d4.attitude_incentive_key FULL OUTER JOIN LH_EV_Silver.dbo.silver_train_pending_star_v2 s ON f.id=s.id WHERE f.id IS NULL OR s.id IS NULL OR f.Age <> s.Age OR f.Age IS NULL OR s.Age IS NULL OR f.Annual_Income_USD <> s.Annual_Income_USD OR f.Annual_Income_USD IS NULL OR s.Annual_Income_USD IS NULL OR f.Daily_Commute_km <> s.Daily_Commute_km OR f.Daily_Commute_km IS NULL OR s.Daily_Commute_km IS NULL OR f.Number_of_Cars_Owned <> s.Number_of_Cars_Owned OR f.Number_of_Cars_Owned IS NULL OR s.Number_of_Cars_Owned IS NULL OR f.Charging_Stations_Near_Home <> s.Charging_Stations_Near_Home OR f.Charging_Stations_Near_Home IS NULL OR s.Charging_Stations_Near_Home IS NULL OR f.Charging_Stations_Near_Work <> s.Charging_Stations_Near_Work OR f.Charging_Stations_Near_Work IS NULL OR s.Charging_Stations_Near_Work IS NULL OR f.Will_Buy_EV <> s.Will_Buy_EV OR f.Will_Buy_EV IS NULL OR s.Will_Buy_EV IS NULL OR f.will_buy_ev_flag <> s.will_buy_ev_flag OR f.will_buy_ev_flag IS NULL OR s.will_buy_ev_flag IS NULL OR d0.Gender <> s.Gender OR d0.Gender IS NULL OR s.Gender IS NULL OR d0.City_Type <> s.City_Type OR d0.City_Type IS NULL OR s.City_Type IS NULL OR d2.Current_Car_Type <> s.Current_Car_Type OR d2.Current_Car_Type IS NULL OR s.Current_Car_Type IS NULL OR d3.Home_Charging_Possible <> s.Home_Charging_Possible OR d3.Home_Charging_Possible IS NULL OR s.Home_Charging_Possible IS NULL OR d4.Environmental_Concern_Level <> s.Environmental_Concern_Level OR d4.Environmental_Concern_Level IS NULL OR s.Environmental_Concern_Level IS NULL OR d4.Subsidy_Available <> s.Subsidy_Available OR d4.Subsidy_Available IS NULL OR s.Subsidy_Available IS NULL OR d4.Range_Anxiety_Level <> s.Range_Anxiety_Level OR d4.Range_Anxiety_Level IS NULL OR s.Range_Anxiety_Level IS NULL;
